# Generated by Django 3.1.3 on 2021-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='buttonclicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='lifetimeearning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='lifetimespent',
            field=models.IntegerField(default=0),
        ),
    ]
